package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

/**
 * CatComprasId generated by hbm2java
 */
public class CatComprasId implements java.io.Serializable {

	private int idCompras;
	private int idProducto;

	public CatComprasId() {
	}

	public CatComprasId(int idCompras, int idProducto) {
		this.idCompras = idCompras;
		this.idProducto = idProducto;
	}

	public int getIdCompras() {
		return this.idCompras;
	}

	public void setIdCompras(int idCompras) {
		this.idCompras = idCompras;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatComprasId))
			return false;
		CatComprasId castOther = (CatComprasId) other;

		return (this.getIdCompras() == castOther.getIdCompras()) && (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCompras();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
