package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * CatCompras generated by hbm2java
 */
public class CatCompras implements java.io.Serializable {

	private CatComprasId id;
	private Compras compras;
	private CatProductos catProductos;
	private Integer cantidad;
	private BigDecimal PCompra;
	private BigDecimal PVenta;
	private BigDecimal subTotal;
	private Integer status;

	public CatCompras() {
	}

	public CatCompras(CatComprasId id, Compras compras, CatProductos catProductos) {
		this.id = id;
		this.compras = compras;
		this.catProductos = catProductos;
	}

	public CatCompras(CatComprasId id, Compras compras, CatProductos catProductos, Integer cantidad, BigDecimal PCompra,
			BigDecimal subTotal, Integer status, BigDecimal PVenta) {
		this.id = id;
		this.compras = compras;
		this.catProductos = catProductos;
		this.cantidad = cantidad;
		this.PCompra = PCompra;
		this.PVenta = PVenta;
		this.subTotal = subTotal;
		this.status = status;
	}

	public CatComprasId getId() {
		return this.id;
	}

	public void setId(CatComprasId id) {
		this.id = id;
	}

	public Compras getCompras() {
		return this.compras;
	}

	public void setCompras(Compras compras) {
		this.compras = compras;
	}

	public CatProductos getCatProductos() {
		return this.catProductos;
	}

	public void setCatProductos(CatProductos catProductos) {
		this.catProductos = catProductos;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPCompra() {
		return this.PCompra;
	}

	public void setPCompra(BigDecimal PCompra) {
		this.PCompra = PCompra;
	}

	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public BigDecimal getPVenta() {
		return PVenta;
	}

	public void setPVenta(BigDecimal pVenta) {
		PVenta = pVenta;
	}

	
	
}
