package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CatMovCaja generated by hbm2java
 */
public class CatMovCaja implements java.io.Serializable {

	private int idMovimiento;
	private String descripcion;
	private Integer status;
	private Integer afectacion;
	private Set movimientoCajas = new HashSet(0);
	private Set movimientoCajaHistoricases = new HashSet(0);

	public CatMovCaja() {
	}

	public CatMovCaja(int idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public CatMovCaja(int idMovimiento, String descripcion, Integer status, Integer afectacion, Set movimientoCajas,
			Set movimientoCajaHistoricases) {
		this.idMovimiento = idMovimiento;
		this.descripcion = descripcion;
		this.status = status;
		this.afectacion = afectacion;
		this.movimientoCajas = movimientoCajas;
		this.movimientoCajaHistoricases = movimientoCajaHistoricases;
	}

	public int getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(int idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getAfectacion() {
		return this.afectacion;
	}

	public void setAfectacion(Integer afectacion) {
		this.afectacion = afectacion;
	}

	public Set getMovimientoCajas() {
		return this.movimientoCajas;
	}

	public void setMovimientoCajas(Set movimientoCajas) {
		this.movimientoCajas = movimientoCajas;
	}

	public Set getMovimientoCajaHistoricases() {
		return this.movimientoCajaHistoricases;
	}

	public void setMovimientoCajaHistoricases(Set movimientoCajaHistoricases) {
		this.movimientoCajaHistoricases = movimientoCajaHistoricases;
	}

}
