package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatProductos generated by hbm2java
 */
public class CatProductos implements java.io.Serializable {

	private Integer idProducto;
	private CatUnidadMedida catUnidadMedida;
	private String descProducto;
	private Integer cantidad;
	private BigDecimal PUCompra;
	private BigDecimal PUVenta;
	private Integer minimo;
	private Integer iva;
	private BigDecimal PUMayoreo;
	private BigDecimal PSMayoreo;
	private Integer factor;
	private Long codigoBarras;
	private Integer idTipoAbastecimiento;
	private CatProveedor catProveedor;
	private CatCategoria catCategoria;
	private boolean faltante;

	public CatProductos() {
	}


	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public CatUnidadMedida getCatUnidadMedida() {
		if(this.catUnidadMedida == null){
			return new CatUnidadMedida();
		}
		
		return this.catUnidadMedida;
	}

	public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
		this.catUnidadMedida = catUnidadMedida;
	}

	public String getDescProducto() {
		return this.descProducto;
	}

	public void setDescProducto(String descProducto) {
		this.descProducto = descProducto;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPUCompra() {
		return this.PUCompra;
	}

	public void setPUCompra(BigDecimal PUCompra) {
		this.PUCompra = PUCompra;
	}

	public BigDecimal getPUVenta() {
		return this.PUVenta;
	}

	public void setPUVenta(BigDecimal PUVenta) {
		this.PUVenta = PUVenta;
	}

	public Integer getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Integer minimo) {
		this.minimo = minimo;
	}

	public Integer getIva() {
		return this.iva;
	}

	public void setIva(Integer iva) {
		this.iva = iva;
	}

	public BigDecimal getPUMayoreo() {
		return this.PUMayoreo;
	}

	public void setPUMayoreo(BigDecimal PUMayoreo) {
		this.PUMayoreo = PUMayoreo;
	}

	public BigDecimal getPSMayoreo() {
		return this.PSMayoreo;
	}

	public void setPSMayoreo(BigDecimal PSMayoreo) {
		this.PSMayoreo = PSMayoreo;
	}

	public Integer getFactor() {
		return this.factor;
	}

	public void setFactor(Integer factor) {
		this.factor = factor;
	}

	public Long getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(Long codigoBarras) {
		this.codigoBarras = codigoBarras;
	}


	public Integer getIdTipoAbastecimiento() {
		return idTipoAbastecimiento;
	}


	public void setIdTipoAbastecimiento(Integer idTipoAbastecimiento) {
		this.idTipoAbastecimiento = idTipoAbastecimiento;
	}


	public CatProveedor getCatProveedor() {
		return catProveedor;
	}


	public void setCatProveedor(CatProveedor catProveedor) {
		this.catProveedor = catProveedor;
	}


	public CatCategoria getCatCategoria() {
		return catCategoria;
	}


	public void setCatCategoria(CatCategoria catCategoria) {
		this.catCategoria = catCategoria;
	}


	public boolean isFaltante() {
		return faltante;
	}


	public void setFaltante(boolean faltante) {
		this.faltante = faltante;
	}

	

}
