package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CatUnidadMedida generated by hbm2java
 */
public class CatUnidadMedida implements java.io.Serializable {

	private Integer idUnidadMedida;
	private String desUnidadMedida;
	private Set catProductoses = new HashSet(0);

	public CatUnidadMedida() {
	}

	public CatUnidadMedida(String desUnidadMedida, Set catProductoses) {
		this.desUnidadMedida = desUnidadMedida;
		this.catProductoses = catProductoses;
	}

	public Integer getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(Integer idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	public String getDesUnidadMedida() {
		return this.desUnidadMedida;
	}

	public void setDesUnidadMedida(String desUnidadMedida) {
		this.desUnidadMedida = desUnidadMedida;
	}

	public Set getCatProductoses() {
		return this.catProductoses;
	}

	public void setCatProductoses(Set catProductoses) {
		this.catProductoses = catProductoses;
	}

}
