package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * CatVentas generated by hbm2java
 */
public class CatVentas implements java.io.Serializable {

	
	private Ventas ventas;
	private CatProductos catProductos;
	private Integer cantidad;
	private BigDecimal PUnitario;
	private BigDecimal subTotal;
	private Integer status;
	private Date fechaLiq;

	public CatVentas() {
	}

	

	
	public Ventas getVentas() {
		return this.ventas;
	}

	public void setVentas(Ventas ventas) {
		this.ventas = ventas;
	}

	public CatProductos getCatProductos() {
		return this.catProductos;
	}

	public void setCatProductos(CatProductos catProductos) {
		this.catProductos = catProductos;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPUnitario() {
		return this.PUnitario;
	}

	public void setPUnitario(BigDecimal PUnitario) {
		this.PUnitario = PUnitario;
	}

	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getFechaLiq() {
		return this.fechaLiq;
	}

	public void setFechaLiq(Date fechaLiq) {
		this.fechaLiq = fechaLiq;
	}

}
