package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

/**
 * CatVentasId generated by hbm2java
 */
public class CatVentasId implements java.io.Serializable {

	private int idProducto;
	private int folio;

	public CatVentasId() {
	}

	public CatVentasId(int idProducto, int folio) {
		this.idProducto = idProducto;
		this.folio = folio;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public int getFolio() {
		return this.folio;
	}

	public void setFolio(int folio) {
		this.folio = folio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatVentasId))
			return false;
		CatVentasId castOther = (CatVentasId) other;

		return (this.getIdProducto() == castOther.getIdProducto()) && (this.getFolio() == castOther.getFolio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProducto();
		result = 37 * result + this.getFolio();
		return result;
	}

}
