package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

/**
 * CatVentasHistoricas generated by hbm2java
 */
public class CatVentasHistoricas implements java.io.Serializable {

	private CatVentasHistoricasId id;
	private CatProductos catProductos;

	public CatVentasHistoricas() {
	}

	public CatVentasHistoricas(CatVentasHistoricasId id, CatProductos catProductos) {
		this.id = id;
		this.catProductos = catProductos;
	}

	public CatVentasHistoricasId getId() {
		return this.id;
	}

	public void setId(CatVentasHistoricasId id) {
		this.id = id;
	}

	public CatProductos getCatProductos() {
		return this.catProductos;
	}

	public void setCatProductos(CatProductos catProductos) {
		this.catProductos = catProductos;
	}

}
