package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CentroVenta generated by hbm2java
 */
public class CentroVenta implements java.io.Serializable {

	private int idCve;
	private String nombre;
	private String rfc;
	private String domicilio;
	private Date fechaLiq;

	public CentroVenta() {
	}

	public CentroVenta(int idCve) {
		this.idCve = idCve;
	}

	public CentroVenta(int idCve, String nombre, String rfc, String domicilio, Date fechaLiq) {
		this.idCve = idCve;
		this.nombre = nombre;
		this.rfc = rfc;
		this.domicilio = domicilio;
		this.fechaLiq = fechaLiq;
	}

	public int getIdCve() {
		return this.idCve;
	}

	public void setIdCve(int idCve) {
		this.idCve = idCve;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public Date getFechaLiq() {
		return this.fechaLiq;
	}

	public void setFechaLiq(Date fechaLiq) {
		this.fechaLiq = fechaLiq;
	}

}
