package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compras generated by hbm2java
 */
public class Compras implements java.io.Serializable {

	private Integer idCompras;
	private Documento documento;
	private Date fecha;
	private Integer idUsuario;
	private BigDecimal total;
	private BigDecimal subTotal;
	private BigDecimal iva;
	private Integer status;
	private String nota;
	private Set catComprases = new HashSet(0);

	public Compras() {
	}

	public Compras(Documento documento, Date fecha, Integer idUsuario, BigDecimal total, BigDecimal subTotal,
			BigDecimal iva, Integer status, String nota, Set catComprases) {
		this.documento = documento;
		this.fecha = fecha;
		this.idUsuario = idUsuario;
		this.total = total;
		this.subTotal = subTotal;
		this.iva = iva;
		this.status = status;
		this.nota = nota;
		this.catComprases = catComprases;
	}

	public Integer getIdCompras() {
		return this.idCompras;
	}

	public void setIdCompras(Integer idCompras) {
		this.idCompras = idCompras;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	public Set getCatComprases() {
		return this.catComprases;
	}

	public void setCatComprases(Set catComprases) {
		this.catComprases = catComprases;
	}

}
