package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Documento generated by hbm2java
 */
public class Documento implements java.io.Serializable {

	private int idDoc;
	private String documento;
	private String descripcion;
	private Set ventases = new HashSet(0);
	private Set comprases = new HashSet(0);

	public Documento() {
	}

	public Documento(int idDoc) {
		this.idDoc = idDoc;
	}

	public Documento(int idDoc, String documento, String descripcion, Set ventases, Set comprases) {
		this.idDoc = idDoc;
		this.documento = documento;
		this.descripcion = descripcion;
		this.ventases = ventases;
		this.comprases = comprases;
	}

	public int getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(int idDoc) {
		this.idDoc = idDoc;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}

}
