package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos implements java.io.Serializable {

	private Integer idMovimientos;
	private CatProductos catProductos;
	private Integer entra;
	private Integer sale;
	private String referencia;
	private Date fecha;
	private Integer idVentaCompra;

	public Movimientos() {
	}

	public Movimientos(CatProductos catProductos, Integer entra, Integer sale, String referencia, Date fecha,
			Integer idVentaCompra) {
		this.catProductos = catProductos;
		this.entra = entra;
		this.sale = sale;
		this.referencia = referencia;
		this.fecha = fecha;
		this.idVentaCompra = idVentaCompra;
	}

	public Integer getIdMovimientos() {
		return this.idMovimientos;
	}

	public void setIdMovimientos(Integer idMovimientos) {
		this.idMovimientos = idMovimientos;
	}

	public CatProductos getCatProductos() {
		return this.catProductos;
	}

	public void setCatProductos(CatProductos catProductos) {
		this.catProductos = catProductos;
	}

	public Integer getEntra() {
		return this.entra;
	}

	public void setEntra(Integer entra) {
		this.entra = entra;
	}

	public Integer getSale() {
		return this.sale;
	}

	public void setSale(Integer sale) {
		this.sale = sale;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getIdVentaCompra() {
		return this.idVentaCompra;
	}

	public void setIdVentaCompra(Integer idVentaCompra) {
		this.idVentaCompra = idVentaCompra;
	}

}
