package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovimientoCaja generated by hbm2java
 */
public class MovimientoCaja implements java.io.Serializable {

	private Integer idMovCaja;
	private CatMovCaja catMovCaja;
	private Usuario usuario;
	private BigDecimal monto;
	private String comentario;
	private Date fecha;
	private Set ventases = new HashSet(0);

	public MovimientoCaja() {
	}

	public MovimientoCaja(CatMovCaja catMovCaja, Usuario usuario, BigDecimal monto, String comentario, Date fecha,
			Set ventases) {
		this.catMovCaja = catMovCaja;
		this.usuario = usuario;
		this.monto = monto;
		this.comentario = comentario;
		this.fecha = fecha;
		this.ventases = ventases;
	}

	public Integer getIdMovCaja() {
		return this.idMovCaja;
	}

	public void setIdMovCaja(Integer idMovCaja) {
		this.idMovCaja = idMovCaja;
	}

	public CatMovCaja getCatMovCaja() {
		return this.catMovCaja;
	}

	public void setCatMovCaja(CatMovCaja catMovCaja) {
		this.catMovCaja = catMovCaja;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

}
