package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovimientoCajaHistoricas generated by hbm2java
 */
public class MovimientoCajaHistoricas implements java.io.Serializable {

	private int idMovCaja;
	private CatMovCaja catMovCaja;
	private Usuario usuario;
	private BigDecimal monto;
	private String comentario;
	private Date fecha;
	private Set ventasHistoricases = new HashSet(0);

	public MovimientoCajaHistoricas() {
	}

	public MovimientoCajaHistoricas(int idMovCaja) {
		this.idMovCaja = idMovCaja;
	}

	public MovimientoCajaHistoricas(int idMovCaja, CatMovCaja catMovCaja, Usuario usuario, BigDecimal monto,
			String comentario, Date fecha, Set ventasHistoricases) {
		this.idMovCaja = idMovCaja;
		this.catMovCaja = catMovCaja;
		this.usuario = usuario;
		this.monto = monto;
		this.comentario = comentario;
		this.fecha = fecha;
		this.ventasHistoricases = ventasHistoricases;
	}

	public int getIdMovCaja() {
		return this.idMovCaja;
	}

	public void setIdMovCaja(int idMovCaja) {
		this.idMovCaja = idMovCaja;
	}

	public CatMovCaja getCatMovCaja() {
		return this.catMovCaja;
	}

	public void setCatMovCaja(CatMovCaja catMovCaja) {
		this.catMovCaja = catMovCaja;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getVentasHistoricases() {
		return this.ventasHistoricases;
	}

	public void setVentasHistoricases(Set ventasHistoricases) {
		this.ventasHistoricases = ventasHistoricases;
	}

}
