package com.puntoventa.hibernate;

// Generated 10/09/2015 10:56:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * Prueba generated by hbm2java
 */
public class Prueba implements java.io.Serializable {

	private int idPrueba;

	public Prueba() {
	}

	public Prueba(int idPrueba) {
		this.idPrueba = idPrueba;
	}

	public int getIdPrueba() {
		return this.idPrueba;
	}

	public void setIdPrueba(int idPrueba) {
		this.idPrueba = idPrueba;
	}

}
