package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

/**
 * VwVentas generated by hbm2java
 */
public class VwVentas implements java.io.Serializable {

	private VwVentasId id;

	public VwVentas() {
	}

	public VwVentas(VwVentasId id) {
		this.id = id;
	}

	public VwVentasId getId() {
		return this.id;
	}

	public void setId(VwVentasId id) {
		this.id = id;
	}

}
