package com.puntoventa.hibernate;
// Generated 27/11/2015 03:27:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * VwVentasId generated by hbm2java
 */
public class VwVentasId implements java.io.Serializable {

	private BigDecimal total;
	private Date fechaLiq;

	public VwVentasId() {
	}

	public VwVentasId(BigDecimal total, Date fechaLiq) {
		this.total = total;
		this.fechaLiq = fechaLiq;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public Date getFechaLiq() {
		return this.fechaLiq;
	}

	public void setFechaLiq(Date fechaLiq) {
		this.fechaLiq = fechaLiq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwVentasId))
			return false;
		VwVentasId castOther = (VwVentasId) other;

		return ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null && castOther.getTotal() != null
				&& this.getTotal().equals(castOther.getTotal())))
				&& ((this.getFechaLiq() == castOther.getFechaLiq()) || (this.getFechaLiq() != null
						&& castOther.getFechaLiq() != null && this.getFechaLiq().equals(castOther.getFechaLiq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getFechaLiq() == null ? 0 : this.getFechaLiq().hashCode());
		return result;
	}

}
